
baseURL = "https://ratfl.github.io/Netrunner/"
languageCode = "es"
title = "The Netrunner Blog"
theme = "hugo-theme-terminal"

[params]
  [params.logo]
    text = "The Netrunner Blog"

  subtitle = "Walkthroughs, laboratorios y análisis de Ciberseguridad"
  description = "Walkthroughs, laboratorios y análisis de ciberseguridad"
  themeColor = "dark"
  showReadingTime = true
  showCodeCopyButtons = true
  customCSS = ["css/custom.css"]
	
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/RaTFl"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ra%C3%BAl-torres-733061400/"

[markup.highlight]
  style = "monokai"
  guessSyntax = true
  tabWidth = 4
  anchorLineNos = true

[outputs]
  home = ["HTML", "RSS"]


